
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: java-app-build
  namespace: bog-dev
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/george-cassar/java-app.git"
    contextDir: "app-code"
  strategy:
    type: "Docker"
    dockerStrategy: {}
  output:
    to:
      kind: "ImageStreamTag"
      name: "java-app:latest"
  triggers:
    - type: "ConfigChange"
