
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app-prd
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/george-cassar/java-app.git'
    targetRevision: main
    path: k8s-manifests/overlays/bog-prd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bog-prd
  syncPolicy:
    automated: null
