
bases:
  - ../../base
namespace: bog-prd
resources:
  - namespace.yaml
  - buildconfig.yaml
  - route.yaml
images:
  - name: "java-app"
    newName: "image-registry.openshift-image-registry.svc:5000/bog-prd/java-app"
    newTag: "latest"
